version: '3'

services:
  journal:
    environment:
      - BIND_ADDRESS=0.0.0.0:5000
      - JWT_SECRET=12345678
    image: daydreamer767910/journal:latest
    container_name: journal-alone
    ports:
      - '5000:5000'
    restart: unless-stopped
    volumes:
      - ./db:/app/db
      - ./public:/app/public
      - ./logs:/app/logs

